AllCops:
  Exclude:
    - spec/dummy/bin/*
    - spec/dummy-*/**/*
  TargetRubyVersion: 2.5

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - spec/spec_helper.rb

Style/NestedParenthesizedCalls:
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Exclude:
    - lib/generators/**/*

Metrics/LineLength:
  Max: 130
