AllCops:
  Exclude:
    - spec/dummy/bin/*
  TargetRubyVersion: 2.5

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - spec/spec_helper.rb

Metrics/LineLength:
  Max: 130
